export default class produtos {
  
  listar(cliente) {
    switch (cliente) {
      case 'MAIS71CLOTHING':        
        return [
          { "nome": "MAIS71CLOTHING 1", "nota": "3", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque  sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo.        Vivamus   ultricies efficitur enim id finibus." },
            { "nome": "MAIS71CLOTHING 2", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo.        Vivamus ultricies efficitur enim id finibus." },
            { "nome": "MAIS71CLOTHING 3", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." },
             { "nome": "MAIS71CLOTHING 4", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." },
              { "nome": "MAIS71CLOTHING 5", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." },
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }
               ,
               { "nome": "MAIS71CLOTHING 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }]

        break;

      case 'SEVEN':
        return [{ "nome": "SEVEN 1", "nota": "3", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }, { "nome": "SEVEN 2", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }, { "nome": "SEVEN 3", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }, { "nome": "SEVEN 4", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }, { "nome": "SEVEN 5", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }, { "nome": "SEVEN 6", "nota": "4.2", "valor": "50.00", "descricao": "Aliquam pulvinar rhoncus massa, ac egestas ante semper sed. Integer tristique neque lectus, maximus convallis neque sollicitudin eget. Phasellus a aliquet purus, in consequat nisl. Cras maximus vehicula ipsum, non venenatis diam varius eleifend. Vivamus a volutpat ante, eu rhoncus eros. Donec eget dictum leo. Vivamus ultricies efficitur enim id finibus." }]
        break;

      default:
        return [];
        break;
    }
  }
}
